tun-device nat64    #name of the TUN device to create for the NAT64 interface
ipv4-addr 192.168.255.1     # IPv4 address to use for tayga
prefix 2001:db8:1:ffff::/96     # prefix to use for IPv6 address mapping
dynamic-pool 192.168.255.0/24   # pool of IPv4 addresses to use for dynamic mapping
data-dir /var/db/tayga          # directory to store tayga's state and mappings